version: '3.8'

services:
  # Database
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: genai_user
      POSTGRES_PASSWORD: genai_password
      POSTGRES_DB: genai_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U genai_user -d genai_assistant"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://genai_user:genai_password@db:5432/genai_assistant
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/app
      - uploaded_files:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  uploaded_files: